apiVersion: v1
kind: Service
metadata:
  name: n8n-svc
  namespace: jsc-ns
  labels:
    app: n8n-app
spec:
  type: ClusterIP
  ports:
    - port: 5678
      targetPort: 5678
  selector:
    app: n8n-app
    tier: frontend
  externalIPs:
    - 192.168.1.133
