apiVersion: v1
kind: Service
metadata:
  name: jsc-cfyui-api-svc
  namespace: jsc-ns
  labels:
    app: jsc-comfyui-app
spec:
  type: ClusterIP
  ports:
    - port: 8889
      targetPort: 3000
  selector:
    app: jsc-comfyui-app
    tier: frontend
  externalIPs:
    - 192.168.1.132
