apiVersion: apps/v1
kind: Deployment
metadata:
  name: narok-wp
  namespace: jsc-ns
  labels:
    app: narok-wp
spec:
  selector:
    matchLabels:
      app: narok-wp
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      namespace: jsc-ns
      labels:
        app: narok-wp
        tier: frontend
    spec:
      containers:
        - image: wordpress:latest
          name: narok-wp
          resources:
            requests:
              ephemeral-storage: "1Gi"
              memory: "250Mi"
            limits:
              ephemeral-storage: "2Gi"
              memory: "300Mi"
          env:
            - name: TZ
              value: Asia/Bangkok
            - name: WORDPRESS_DB_HOST
              value: narok-wp-mariadb
            - name: WORDPRESS_DB_NAME
              value: narok-wp-db
            - name: WORDPRESS_DB_USER
              value: narok-wp-user
            - name: WORDPRESS_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: narok-secret
                  key: wp_password
          ports:
            - containerPort: 80
              name: narok-wp
          volumeMounts:
            - name: narok-wp-persistent-storage
              mountPath: /var/www/html
            - name: narok-wp-apache-config-json
              mountPath: /etc/apache2/conf-enabled/log.conf
              subPath: log.conf
            - name: narok-wp-apache-config-log
              mountPath: /etc/apache2/sites-available/000-default.conf
              subPath: 000-default.conf
      volumes:
        - name: narok-wp-persistent-storage
          persistentVolumeClaim:
            claimName: narok-wp-pv-claim
        - name: narok-wp-apache-config-json
          configMap:
            name: narok-wp-apache-configmap
            items:
              - key: log.conf
                path: log.conf
        - name: narok-wp-apache-config-log
          configMap:
            name: narok-wp-apache-configmap
            items:
              - key: 000-default.conf
                path: 000-default.conf
